parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $translator: "@app.google_translator"

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    app.google_translator:
        class: AppBundle\Service\Bridges\GoogleTranslatorBridge
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%google_translate%"
